### ISSUE TITLE
@foundryvtt/pdfjs not found

### ISSUE THREAD

**Issue by numinit** [reckenrode/nix-foundryvtt#1]
Hi there,

Foundry 10 includes a dependency on a fork of pdfjs that doesn't seem to be public, but is distributed in the source zipball: @foundryvtt/pdfjs. Therefore the Foundry 10 build fails because it can't pinpoint this dependency.

Do you have any suggestsions?

Thanks,
Morgan

**Comment by reckenrode** [comment]
The repository is available at [foundryvtt/pdfjs][1], but the release isn’t tagged. If you change the reference in `package.json` to point to the Git repo, then `node2nix` can regenerate the dependencies expression properly. You don’t need to patch the file in the build (just when regenerating the dependencies). It’s not ideal, but it gets the job done.

Alternatively, you could also just delete the whole `node2nix` stuff and copy `node_modules` from the upstream zip file. Since you’re parameterizing the expression in your fork, that might be a better approach (otherwise you’d potentially need a set of dependencies for each version).

I’ve got a couple of commits that fix the dependencies and update the derivation that I’ll be pushing shortly.

```json
"@foundryvtt/pdfjs": "git+https://github.com/foundryvtt/pdfjs.git#2196ae9bcbd8d6a9b0b9c493d0e9f3aca13f2fd9",
```

[1]: https://github.com/foundryvtt/pdfjs

**Comment by numinit** [comment]
Thanks!

**Comment by reckenrode** [comment]
@numinit FYI, there’s a possibility we’re going to be using Foundry again, so I’ve unarchived to bump the version. I’ve subscribed to the Foundry repo to try to do a better job keeping things updated.

It also looks like node2nix works with newer Node versions now, so I’ve updated the derivation a bit. It’s still the same though. I’m probably not going to allow arbitrary versions due to how Foundry updates its `node_modules` with each release, so I’d recommend keeping your fork (@-mentioning as a heads up).
